CREATE DATABASE SYDENHAM_DB;
GO

USE SYDENHAM_DB;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'LIBRARY_BOOK')
BEGIN
    CREATE TABLE LIBRARY_BOOK
    (
        BOOK_ID INT PRIMARY KEY IDENTITY,
        BOOK_REFERENCE_NUMBER NVARCHAR(50) NOT NULL, 
        TITLE NVARCHAR(255) NOT NULL,
        ISBN NVARCHAR(20) NOT NULL UNIQUE,
        AUTHOR NVARCHAR(255) NOT NULL,
        PUBLICATION NVARCHAR(255),
        EDITION NVARCHAR(50),
        PUBLISHED_YEAR INT,
        CATEGORY NVARCHAR(100),
		NO_OF_COPY INT,
		AVAILBLE_COPY INT
    );
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'LIBRARY_GUEST')
BEGIN
CREATE TABLE LIBRARY_GUEST (
    GUEST_ID INT PRIMARY KEY IDENTITY,
    ID_NUMBER NVARCHAR(15) NOT NULL,  
    FIRST_NAME NVARCHAR(100) NOT NULL,
    LAST_NAME NVARCHAR(100) NOT NULL,
    EMAIL NVARCHAR(255) NOT NULL UNIQUE,
    ADDRESS NVARCHAR(255),
    TELEPHONE NVARCHAR(20),
    REGISTERED_DATE DATE NOT NULL,
    TERMINATED_DATE DATE
);
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'LIBRARY_ISSUE_BOOKS')
BEGIN
CREATE TABLE LIBRARY_ISSUE_BOOKS (
    ISSUE_ID INT PRIMARY KEY IDENTITY,
    BOOK_ID INT NOT NULL,
    GUEST_ID INT NOT NULL,
    ISSUE_DATE DATE NOT NULL,
    RETURN_DATE DATE NOT NULL,
    FOREIGN KEY (BOOK_ID) REFERENCES LIBRARY_BOOK(BOOK_ID),
	FOREIGN KEY (GUEST_ID) REFERENCES LIBRARY_GUEST(GUEST_ID)
);
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'LIBRARY_CD')
BEGIN
    CREATE TABLE LIBRARY_CD
    (
        CD_ID INT PRIMARY KEY IDENTITY,
        CD_TITLE NVARCHAR(255) NOT NULL,
        AUTHOR NVARCHAR(255) NOT NULL,
        PUBLICATION NVARCHAR(255),
        PRINTED_YEAR INT,
        CATEGORY NVARCHAR(100)
    );
END
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'LIBRARY_ADMIN')
BEGIN
    CREATE TABLE LIBRARY_ADMIN
    (
        USER_ID NVARCHAR(100) PRIMARY KEY NOT NULL,
        PASSWORD NVARCHAR(100) NOT NULL
    );
END
GO

IF NOT EXISTS (SELECT * FROM sys.procedures WHERE name = 'SearchBooks')
BEGIN
    EXEC('
    CREATE PROCEDURE SearchBooks
        @BookReferenceNumber VARCHAR(50) = NULL,
        @BookTitle VARCHAR(100) = NULL,
        @Author VARCHAR(100) = NULL
    AS
    BEGIN
        SELECT 
            b.BOOK_REFERENCE_NUMBER, b.TITLE, b.PUBLICATION, b.AUTHOR, 
            s.FIRST_NAME + '' '' + s.LAST_NAME AS GUESTName, 
            ib.ISSUE_DATE, ib.RETURN_DATE
        FROM LIBRARY_BOOK b
        LEFT JOIN LIBRARY_ISSUE_BOOKS ib ON b.BOOK_ID = ib.BOOK_ID
        LEFT JOIN LIBRARY_GUEST s ON ib.GUEST_ID = s.GUEST_ID
        WHERE (@BookReferenceNumber IS NULL OR b.BOOK_REFERENCE_NUMBER = @BookReferenceNumber)
          AND (@BookTitle IS NULL OR b.TITLE LIKE ''%'' + @BookTitle + ''%'')
          AND (@Author IS NULL OR b.AUTHOR LIKE ''%'' + @Author + ''%'');
    END
    ')
END
GO

